const navItems = ['About', 'Skills', 'Experience', 'Projects', 'Contact'];
const skills = ['Next.js','React','TypeScript','Tailwind CSS','Node.js','API Design','Conversational AI','Automation','Data Pipelines','Dashboard UX','Cloud Deployment','GitHub Actions'];
const projects = [
  { name: 'Axify Portal', repo: 'Axify-Portal', link: 'https://github.com/hanchengxuan/Axify-Portal', summary: 'A portal-style web application focused on clean product workflows, reusable UI structure, and practical business operations.' },
  { name: 'Conversational AI', repo: 'conversational-ai', link: 'https://github.com/hanchengxuan/conversational-ai', summary: 'Experiments and implementation work around AI assistants, dialogue flows, retrieval patterns, and human-friendly automation.' },
  { name: 'Call Log Processing', repo: 'call-log-processing', link: 'https://github.com/hanchengxuan/call-log-processing', summary: 'Processing pipelines for call-log data, turning raw operational records into structured insight and analysis-ready outputs.' }
];
const experience = [
  'Built production-grade web modules with React/Next.js-style architecture, API integrations, and deployment-aware frontend workflows.',
  'Worked across AI automation, operational data processing, and internal portal tooling where reliability and clarity matter more than flashy demos.',
  'Most production and company repositories are private, but the public repos above show the themes: practical systems, AI-enabled workflows, and useful interfaces.'
];
function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-24 border border-terminal/20 bg-black/35 p-6 shadow-glow backdrop-blur md:p-8"><p className="mb-2 text-xs uppercase tracking-[0.35em] text-terminal/70">{eyebrow}</p><h2 className="mb-6 text-2xl font-bold text-white md:text-3xl">{title}</h2>{children}</section>; }
export default function Home() {
  return <main className="mx-auto min-h-screen max-w-6xl px-4 py-6 md:px-8 md:py-10">
    <nav className="sticky top-4 z-10 mb-10 flex flex-wrap items-center justify-between gap-4 border border-terminal/25 bg-void/85 px-4 py-3 backdrop-blur"><a href="#top" className="text-sm font-bold text-terminal">~/liam-han</a><div className="flex flex-wrap gap-3 text-xs text-terminal/75 md:text-sm">{navItems.map((item) => <a key={item} href={'#' + item.toLowerCase()} className="hover:text-white">{item}</a>)}<a href="/resume-liam-han.txt" download className="text-white hover:text-terminal">Resume</a></div></nav>
    <header id="top" className="mb-12 grid gap-8 md:grid-cols-[1.25fr_0.75fr] md:items-center"><div><p className="mb-4 text-terminal">$ whoami</p><h1 className="text-4xl font-black leading-tight text-white md:text-6xl">Liam <span className="text-terminal">(Chengxuan)</span> Han</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-emerald-100/80">Software engineer building hacker-clean web products, AI workflows, and data automation systems that move from prototype to production.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="border border-terminal bg-terminal px-5 py-3 text-sm font-bold text-black hover:bg-white">View Projects</a><a href="/resume-liam-han.txt" download className="border border-terminal/50 px-5 py-3 text-sm font-bold text-terminal hover:border-white hover:text-white">Download Resume</a></div></div><div className="border border-terminal/25 bg-black/50 p-5 text-sm leading-7 text-terminal/85 shadow-glow"><p className="text-white">system.status</p><p>{'>'} role: software_engineer</p><p>{'>'} focus: ai + web + automation</p><p>{'>'} deploy: vercel_primary</p><p>{'>'} fallback: github_pages_static_export</p><p className="mt-4 animate-pulse text-terminal">connection established_</p></div></header>
    <div className="grid gap-6">
      <Section id="about" eyebrow="01 // About" title="Builder mindset, production bias."><p className="max-w-3xl leading-8 text-emerald-100/80">I like systems that feel sharp on the surface and dependable underneath: clean interfaces, automation that removes repetitive work, and AI features that actually help users finish a job. My public work highlights selected experiments and tools; much of my production/company code lives in private repositories.</p></Section>
      <Section id="skills" eyebrow="02 // Skills" title="Stack and operating mode."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{skills.map((skill) => <div key={skill} className="border border-terminal/15 bg-emerald-950/20 px-4 py-3 text-sm text-emerald-50/85"># {skill}</div>)}</div></Section>
      <Section id="experience" eyebrow="03 // Experience" title="Private repos, real-world systems."><ul className="space-y-4 text-emerald-100/80">{experience.map((item) => <li key={item} className="border-l-2 border-terminal/60 pl-4 leading-7">{item}</li>)}</ul></Section>
      <Section id="projects" eyebrow="04 // Projects" title="Selected public repositories."><div className="grid gap-4 md:grid-cols-3">{projects.map((project) => <article key={project.repo} className="flex min-h-64 flex-col border border-terminal/20 bg-black/45 p-5 transition hover:-translate-y-1 hover:border-terminal"><p className="text-xs uppercase tracking-[0.25em] text-terminal/60">{project.repo}</p><h3 className="mt-3 text-xl font-bold text-white">{project.name}</h3><p className="mt-4 flex-1 leading-7 text-emerald-100/75">{project.summary}</p><a href={project.link} target="_blank" rel="noreferrer" className="mt-5 text-sm font-bold text-terminal hover:text-white">open repo →</a></article>)}</div></Section>
      <Section id="contact" eyebrow="05 // Contact" title="Open a secure channel."><div className="grid gap-4 md:grid-cols-3"><a className="border border-terminal/20 bg-black/40 p-5 hover:border-terminal" href="mailto:hanchengxuan98@gmail.com"><span className="block text-terminal">email</span>hanchengxuan98@gmail.com</a><a className="border border-terminal/20 bg-black/40 p-5 hover:border-terminal" href="https://github.com/hanchengxuan" target="_blank" rel="noreferrer"><span className="block text-terminal">github</span>@hanchengxuan</a><a className="border border-terminal/20 bg-black/40 p-5 hover:border-terminal" href="https://www.linkedin.com/in/chengxuan-han" target="_blank" rel="noreferrer"><span className="block text-terminal">linkedin</span>/in/chengxuan-han</a></div></Section>
    </div><footer className="mt-10 border-t border-terminal/20 py-6 text-xs text-terminal/60">Built with Next.js + Tailwind CSS. Optimized for Vercel, exported statically for GitHub Pages backup.</footer>
  </main>;
}
